version: '3.4'

networks:
  irinetwork:

services:
  rebelswebapi:
    image: ${DOCKER_REGISTRY-}rebelswebapi
    build:
      context: .
      dockerfile: RebelsWebApi/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081
    networks:
        - irinetwork
    depends_on:
        - ms-sql-server 

  securitywebapi:
    image: ${DOCKER_REGISTRY-}securitywebapi
    build:
      context: .
      dockerfile: SecurityWebApi/Dockerfile
    ports:
        - 5002:8080
        - 5003:8081
    networks:
        - irinetwork
    depends_on:
        - ms-sql-server

  configswebapi:
    image: ${DOCKER_REGISTRY-}configswebapi
    build:
      context: .
      dockerfile: ConfigsWebApi/Dockerfile
    ports:
      - 5004:8080
      - 5005:8081
    networks:
        - irinetwork
    depends_on:
        - ms-sql-server

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SApA55w0rd2024"
      MSSQL_PID: Developer
    ports:
        - "1:1433"
    networks:
        - irinetwork

  iriwebapp:
    container_name: iriwebapp
    image: iriwebapp
    build:
      context: .
      dockerfile: WebAppAngularClient/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./WebAppAngularClient:/project
      - /project/node_modules 